<?xml version="1.0" encoding="utf-8"?><Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFramework>net472</TargetFramework><OutputType>Library</OutputType><RootNamespace>HLS_Media_Web_Forms</RootNamespace><OutputPath>bin\</OutputPath><AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath><LangVersion>9.0</LangVersion><AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects><GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType></PropertyGroup><ItemGroup><Reference Include="System.Web" /></ItemGroup><ItemGroup><PackageReference Include="VisioForge.CrossPlatform.Core.Windows.x64" Version="2026.9.11" /><PackageReference Include="VisioForge.CrossPlatform.Libav.Windows.x64.UPX" Version="2026.9.11" /></ItemGroup><ItemGroup><PackageReference Include="VisioForge.DotNet.MediaBlocks" Version="2026.10.10" /><PackageReference Include="VisioForge.DotNet.Core.UI.WebForms" Version="2026.10.10" /></ItemGroup></Project>