<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-ios</TargetFramework>
    <OutputType>Exe</OutputType>
    <Nullable>disable</Nullable>
    <ImplicitUsings>true</ImplicitUsings>
    <SupportedOSPlatformVersion>13.0</SupportedOSPlatformVersion>
    <RuntimeIdentifier>ios-arm64</RuntimeIdentifier>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <CreatePackage>false</CreatePackage>
    <WarningLevel>4</WarningLevel>
    <MtouchLink>SdkOnly</MtouchLink>
    <MtouchInterpreter>all</MtouchInterpreter>
    <MtouchNoSymbolStrip>True</MtouchNoSymbolStrip>
    <MtouchDebug>True</MtouchDebug>
    <DeviceSpecificBuild>true</DeviceSpecificBuild>
    <RunAOTCompilation>true</RunAOTCompilation>
    <MtouchExtraArgs>--verbose</MtouchExtraArgs>
    <IsAotCompatible>true</IsAotCompatible>
    <PublishAot>true</PublishAot>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <CreatePackage>false</CreatePackage>
    <MtouchNoSymbolStrip>True</MtouchNoSymbolStrip>
    <MtouchDebug>False</MtouchDebug>
    <RunAOTCompilation>true</RunAOTCompilation>
    <MtouchExtraArgs>--verbose</MtouchExtraArgs>
    <IsAotCompatible>true</IsAotCompatible>
    <PublishAot>true</PublishAot>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="VisioForge.DotNet.MediaBlocks" Version="2026.10.6" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="VisioForge.CrossPlatform.Core.iOS" Version="2026.9.11" />
  </ItemGroup>
</Project>