name: Build ALL (.Net 8)
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    env:
      Solution_Name_MB1: "Media Blocks SDK/VisioForge.MediaBlocks.Demos.CS net8.sln"      
      Solution_Name_MB2: "Media Blocks SDK/VisioForge.MediaBlocks.Demos.CS Console.sln"
      
      Solution_Name_MP1: "Media Player SDK/VisioForge.MediaPlayer.Demos.CS (NuGet) net8.sln"
      Solution_Name_MP2: "Media Player SDK X/VisioForge.MediaPlayer.X.Demos.CS.Windows net8.sln"    

      Solution_Name_VC1: "Video Capture SDK/VisioForge.VideoCapture.Demos.CS (NuGet) net8.sln"
      Solution_Name_VC2: "Video Capture SDK/VisioForge.VideoCapture.Demos.CS.CV (NuGet) net8.sln"
      Solution_Name_VC3: "Video Capture SDK X/VisioForge.VideoCaptureX.Demos.CS net8.sln"

      Solution_Name_VE1: "Video Edit SDK/VisioForge.VideoEdit.Demos.CS (NuGet) net8.sln"
      Solution_Name_VE2: "Video Edit SDK X/VisioForge.VideoEdit.X.Demos.CS.WinForms net8.sln"  

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET 
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: | 
          8.0.x

    #- name: Install workloads
    #  run: dotnet workload install macos android maui-android maui-maccatalyst ios
          
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
        
    ## Media Blocks

    - name: Restore dependencies $env:Solution_Name_MB1
      run: dotnet restore $env:Solution_Name_MB1

    - name: Build app for release $env:Solution_Name_MB1
      run: msbuild $env:Solution_Name_MB1 -t:rebuild -verbosity:diag -property:Configuration=Release
      
    - name: Restore dependencies $env:Solution_Name_MB2
      run: dotnet restore $env:Solution_Name_MB2

    - name: Build app for release $env:Solution_Name_MB2
      run: msbuild $env:Solution_Name_MB2 -t:rebuild -verbosity:diag -property:Configuration=Release
      
    ## Media Player

    - name: Restore dependencies $env:Solution_Name_MP1
      run: dotnet restore $env:Solution_Name_MP1

    - name: Build app for release $env:Solution_Name_MP1
      run: msbuild $env:Solution_Name_MP1 -t:rebuild -verbosity:diag -property:Configuration=Release

    - name: Restore dependencies $env:Solution_Name_MP2
      run: dotnet restore $env:Solution_Name_MP2

    - name: Build app for release $env:Solution_Name_MP2
      run: msbuild $env:Solution_Name_MP2 -t:rebuild -verbosity:diag -property:Configuration=Release

    ## Video Capture

    - name: Restore dependencies $env:Solution_Name_VC1
      run: dotnet restore $env:Solution_Name_VC1

    - name: Build app for release $env:Solution_Name_VC1
      run: msbuild $env:Solution_Name_VC1 -t:rebuild -verbosity:diag -property:Configuration=Release

    - name: Restore dependencies $env:Solution_Name_VC2
      run: dotnet restore $env:Solution_Name_VC2

    - name: Build app for release $env:Solution_Name_VC2
      run: msbuild $env:Solution_Name_VC2 -t:rebuild -verbosity:diag -property:Configuration=Release

    - name: Restore dependencies $env:Solution_Name_VC3
      run: dotnet restore $env:Solution_Name_VC3

    - name: Build app for release $env:Solution_Name_VC3
      run: msbuild $env:Solution_Name_VC3 -t:rebuild -verbosity:diag -property:Configuration=Release

    ## Video Edit

    - name: Restore dependencies $env:Solution_Name_VE1
      run: dotnet restore $env:Solution_Name_VE1

    - name: Build app for release $env:Solution_Name_VE1
      run: msbuild $env:Solution_Name_VE1 -t:rebuild -verbosity:diag -property:Configuration=Release

    - name: Restore dependencies $env:Solution_Name_VE2
      run: dotnet restore $env:Solution_Name_VE2
      
